### ISSUE TITLE
Configuration parameters have no effect during plugin execution

### ISSUE THREAD

**Issue by jgoldhammer** [chkpnt/truststorebuilder-gradle-plugin#1]
At first thanks for your plugin. 
I want to use it in my gradle build, but currently I am not able to modify the defaults from the plugin.

It seems that the configured values are not used in the plugin execution.

I have prepared a minimal example here: https://github.com/jgoldhammer/truststorebuilder-gradle-plugin-demo

My changes are:
- I have renamed the certs directory to [certs-1](https://github.com/jgoldhammer/truststorebuilder-gradle-plugin-demo/tree/master/src/main/certs-1)
- I have used the new directory certs-1 in [build.gradle](https://github.com/jgoldhammer/truststorebuilder-gradle-plugin-demo/blob/1fcdd01688136e055c3eb3e90fd128e7690f6a4e/build.gradle#L13)

So when entering the command

```
./gradlew buildTrustStore                                                                                    
```

gradle fails with following error message.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/jgoldhammer/dev/source/sandbox/truststorebuilder-gradle-plugin-demo/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'de.chkpnt.truststorebuilder', version: '0.2.57']
> Failed to apply plugin [id 'de.chkpnt.truststorebuilder']
   > Directory '/Users/jgoldhammer/dev/source/sandbox/truststorebuilder-gradle-plugin-demo/src/main/certs' does not exist.
```

Any suggestions here? I guess this is a bug?
Thanks for your help.

**Comment by chkpnt** [comment]
Ups. You are absolutely right. Thanks for pointing that out!

The cause is I'm trying to use the plugin's extension (`trustStoreBuilder { ... }`) during the evaulation phase. That is a fault.

I have an approach to a solution in my mind and hope to find some time for its implemention in the next days.

**Comment by chkpnt** [comment]
Okay, the configuration should now [be respected](https://github.com/chkpnt/truststorebuilder-gradle-plugin/commit/b59cf80e7f65b5fc98eb4277971205025f78dc20#diff-dad2f2a8020e109a8eb0e5ba91b86e5dR98-R146) by the plugin; I've just publish a [new version](https://plugins.gradle.org/plugin/de.chkpnt.truststorebuilder/0.3.94).
